server:
  port: 8080

spring:
  datasource:
    username: hnhskjssws
    password: Hnhskjssws
    url: jdbc:mysql://8.129.86.121:3306/kjssws?useUnicode=true&characterEncoding=utf-8&uesSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: "classpath:/templates/frontend/"
    suffix: ".html"
  resources:
    static-locations: classpath:/static
  redis:
    host: 8.129.86.121
    port: 6379
    database: 10

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.myproject.api.springboot_mybatis.entity

mq:
  nameserver:
    addr: 127.0.0.1:9876
  topicname: stock


#showSql
logging:
  level:
    com:
      example:
        mapper : debug